name: Update generated sources
on: pull_request
jobs:
  update-generated-sources:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'flathubbot'
    steps:
      - name: Install dependencies
        run: |
          sudo apt install -y \
            python3-yaml \
            python3-aiohttp \
            jq

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          submodules: true

      - name: Update generated sources
        env:
          GIT_AUTHOR_NAME: Flatpak External Data Checker
          GIT_COMMITTER_NAME: Flatpak External Data Checker
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
          EMAIL: ${{ github.actor }}@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          ./update-generated-sources.sh
          git push
